site_name: Cartola
repo_url: https://github.com/GMizuno/cartola_project
repo_name: GMizuno/cartola_project
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

watch:
  - cartola_project

plugins:
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [ cartola_project ]


extra:
  commands:
    install: pip install git+ssh://git@github.com/GMizuno/cartola_project.git
    install_mac: pip3 install git+ssh://git@github.com/GMizuno/cartola_project.git


