site_name: Cartola Project
theme:
  name: material

nav:
    - Home: index.md
    - Requester: api/api.md

markdown_extensions:
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight